version: '3.7'
services:
  nginx:
    image: nginx:latest
    ports:
      - '8080:80'
    depends_on:
      - frontend
      - backend
    volumes:
        - ./ngn.conf:/etc/nginx/conf.d/default.conf
        - ./images_iteration_2_2_scaled:/images
  backend:
    image: backend:latest
    build:
      context: ./backend/src
      dockerfile: Dockerfile
    ports:
      - '3001:3000'
    volumes:
      - ./import:/import
    env_file:
      - ./backend/src/.env
    depends_on:
      - db

  frontend:
    image: frontend:latest
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    env_file:
      - ./frontend/.env
  db:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
      MYSQL_USER: test
      MYSQL_PASSWORD: test
    ports:
      - '3306:3306'
    volumes:
      - db-volume:/var/lib/mysql
volumes:
  db-volume: