version: '3.7'
services:
  backend:
    image: backend:latest
    build: ./backend/src
    ports:
      - '3001:3000'
  frontend:
    image: frontend:latest
    build: ./frontend/
    ports:
      - '3000:3000'
  db:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
      MYSQL_USER: test
      MYSQL_PASSWORD: test
    ports:
      - '3306:3306'
